=== Bikisome/tvb-root/framework_tvb/tvb/core/portlets/tvb.xsd
<!--
# -*- coding: utf-8 -*-
#
#
# TheVirtualBrain-Framework Package. This package holds all Data Management, and
# Web-UI helpful to run brain-simulations. To use it, you also need do download
# TheVirtualBrain-Scientific Package (for simulators). See content of the
# documentation-folder for more details. See also http://www.thevirtualbrain.org
#
# (c) 2012-2022, Baycrest Centre for Geriatric Care ("Baycrest") and others
#
# This program is free software: you can redistribute it and/or modify it under the
# terms of the GNU General Public License as published by the Free Software Foundation,
# either version 3 of the License, or (at your option) any later version.
# This program is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.  See the GNU General Public License for more details.
# You should have received a copy of the GNU General Public License along with this
# program.  If not, see <http://www.gnu.org/licenses/>.
#
#
#   CITATION:
# When using The Virtual Brain for scientific publications, please cite it as follows:
#
#   Paula Sanz Leon, Stuart A. Knock, M. Marmaduke Woodman, Lia Domide,
#   Jochen Mersmann, Anthony R. McIntosh, Viktor Jirsa (2013)
#       The Virtual Brain: a simulator of primate brain network dynamics.
#   Frontiers in Neuroinformatics (7:10. doi: 10.3389/fninf.2013.00010)
#
#
-->

<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:annotation>
    	<xs:documentation>
	    	This is a validation XML schema.
			You should use this in case you intend to produce TVB compatible interfaces.
			You are expected to write your algorithms in some programming language (e.g. Matlab, Python) and then describe its interface in an XML file.
			The XML file, if compatible with this XSD, will be parsable by TVB, thus integrated in TVB's UI and results processed by our visualizers.
		</xs:documentation>
	</xs:annotation>

	<xs:simpleType name="alfaNumericString">
		<xs:restriction base="xs:string">
			<xs:minLength value="1" />
			<xs:pattern value="[a-zA-Z0-9]*" />
		</xs:restriction>
	</xs:simpleType>

    <xs:element name="tvb">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="portlet" type="portletType" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="portletType">
        <xs:sequence>
            <xs:element name="inputs" minOccurs="0">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="input" type="inputType" minOccurs="1" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="identifier" type="alfaNumericString" use="required"/>
    </xs:complexType>


    <xs:complexType name="inputType">
        <xs:sequence>
            <xs:element name="name">
                <xs:complexType>
                    <xs:attribute name="value" type="xs:string" use="required"/>
                </xs:complexType>
            </xs:element>
            <xs:element name="label">
                <xs:complexType>
                    <xs:attribute name="value" type="xs:string" use="required"/>
                </xs:complexType>
            </xs:element>
            <xs:element name="description" minOccurs="0">
                <xs:complexType>
                    <xs:attribute name="value" type="xs:string" use="required"/>
                </xs:complexType>
            </xs:element>
            <xs:element name="type" type="type"/>
        </xs:sequence>
        <xs:attribute name="required" use="optional">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="True"/>
                    <xs:enumeration value="False"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="overwrite" type="xs:string" use="optional"/>
    </xs:complexType>


    <xs:complexType name="type">
        <xs:attribute name="value" type="xs:string" use="required"/>
        <xs:attribute name="default" type="xs:string" use="optional"/>
    </xs:complexType>

</xs:schema>

=== Bikisome/tvb-root/framework_tvb/tvb/adapters/portlets/bct_portlets.xml
<!-- -*- coding: utf-8 -*-
#
#
# TheVirtualBrain-Framework Package. This package holds all Data Management, and
# Web-UI helpful to run brain-simulations. To use it, you also need do download
# TheVirtualBrain-Scientific Package (for simulators). See content of the
# documentation-folder for more details. See also http://www.thevirtualbrain.org
#
# (c) 2012-2022, Baycrest Centre for Geriatric Care ("Baycrest") and others
#
# This program is free software: you can redistribute it and/or modify it under the
# terms of the GNU General Public License as published by the Free Software Foundation,
# either version 3 of the License, or (at your option) any later version.
# This program is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.  See the GNU General Public License for more details.
# You should have received a copy of the GNU General Public License along with this
# program.  If not, see <http://www.gnu.org/licenses/>.
#
#
#   CITATION:
# When using The Virtual Brain for scientific publications, please cite it as follows:
#
#   Paula Sanz Leon, Stuart A. Knock, M. Marmaduke Woodman, Lia Domide,
#   Jochen Mersmann, Anthony R. McIntosh, Viktor Jirsa (2013)
#       The Virtual Brain: a simulator of primate brain network dynamics.
#   Frontiers in Neuroinformatics (7:10. doi: 10.3389/fninf.2013.00010)
#
-->

<?xml version="1.0"?>


<tvb xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../core/portlets/tvb.xsd">

    <!--  For each portlet, a preview with the name $identifider$.png should be present in:
        	 tvb/interfaces/static/style/img/portlets 
        	 and a style in section_burst.css
       -->
    <portlet name="BCT - Clustering Coefficient WD" identifier="CCWD">
        <inputs>
            <input>
                <name value="chain_1"/>
                <label value="First adapter from chain"/>
                <type value="tvb.adapters.analyzers.bct_clustering_adapters.ClusteringCoefficientWD" />
            </input>
            <input overwrite="chain_1">
                <name value="connectivity"/>
                <label value="Overwrite with first input of the simulator adapter."/>
                <type value="dynamic" default="step_0[connectivity]"/>
            </input>

            <input>
                <name value="chain_2"/>
                <label value="Second adapter from chain"/>
                <type value="tvb.adapters.visualizers.histogram.HistogramViewer" />
            </input>
            <input overwrite="chain_2">
                <name value="input_data"/>
                <label value="Overwrite input_data parameter of second adapter with the first release of the first adapter."/>
                <type value="dynamic" default="step_1[0]"/>
            </input>
        </inputs>
    </portlet>

    <portlet name="BCT - Node Betweenness Centrality Binary" identifier="NBCB">
        <inputs>
            <input>
                <name value="chain_1"/>
                <label value="First adapter from chain"/>
                <type value="tvb.adapters.analyzers.bct_centrality_adapters.CentralityNodeBinary" />
            </input>
            <input overwrite="chain_1">
                <name value="connectivity"/>
                <label value="Overwrite with first input of the simulator adapter."/>
                <type value="dynamic" default="step_0[connectivity]"/>
            </input>

            <input>
                <name value="chain_2"/>
                <label value="Second adapter from chain"/>
                <type value="tvb.adapters.visualizers.histogram.HistogramViewer"/>
            </input>
            <input overwrite="chain_2">
                <name value="input_data"/>
                <label value="Overwrite input_data parameter of second adapter with the first release of the first adapter."/>
                <type value="dynamic" default="step_1[0]"/>
            </input>
        </inputs>
    </portlet>

    <portlet name="BCT - Instrength and Outstrength" identifier="ISOS">
        <inputs>
            <input>
                <name value="chain_1"/>
                <label value="First adapter from chain"/>
                <type value="tvb.adapters.analyzers.bct_degree_adapters.StrengthISOS"/>
            </input>
            <input overwrite="chain_1">
                <name value="connectivity"/>
                <label value="Overwrite with first input of the simulator adapter."/>
                <type value="dynamic" default="step_0[connectivity]"/>
            </input>

            <input>
                <name value="chain_2"/>
                <label value="Second adapter from chain"/>
                <type value="tvb.adapters.visualizers.histogram.HistogramViewer"/>
            </input>
            <input overwrite="chain_2">
                <name value="input_data"/>
                <label value="Overwrite input_data parameter of second adapter with the first release of the first adapter."/>
                <type value="dynamic" default="step_1[0]"/>
            </input>
        </inputs>
    </portlet>

    <portlet name="BCT - Instrength and Outstrength- Topo" identifier="ISOSTOPO">
        <inputs>
            <input>
                <name value="chain_1"/>
                <label value="First adapter from chain"/>
                <type value="tvb.adapters.analyzers.bct_degree_adapters.StrengthISOS"/>
            </input>
            <input overwrite="chain_1">
                <name value="connectivity"/>
                <label value="Overwrite with first input of the simulator adapter."/>
                <type value="dynamic" default="step_0[connectivity]"/>
            </input>

            <input>
                <name value="chain_2"/>
                <label value="Second adapter from chain"/>
                <type value="tvb.adapters.visualizers.topographic.TopographicViewer"/>
            </input>
            <input overwrite="chain_2">
                <name value="data_0"/>
                <label value="Overwrite data_0 parameter of second adapter with the first release of the first adapter."/>
                <type value="dynamic" default="step_1[0]"/>
            </input>
            <input overwrite="chain_2">
                <name value="data_1"/>
                <label value="Overwrite data_1 parameter of second adapter with the second release of the first adapter."/>
                <type value="dynamic" default="step_1[1]"/>
            </input>
            <input overwrite="chain_2">
                <name value="data_2"/>
                <label value="Overwrite data_2 parameter of second adapter with the third release of the first adapter."/>
                <type value="dynamic" default="step_1[2]"/>
            </input>
        </inputs>
    </portlet>

    <portlet name="BCT - Strength and Weight" identifier="STW">
        <inputs>
            <input>
                <name value="chain_1"/>
                <label value="First adapter from chain"/>
                <type value="tvb.adapters.analyzers.bct_degree_adapters.StrengthWeights" />
            </input>
            <input overwrite="chain_1">
                <name value="connectivity"/>
                <label value="Overwrite with first input of the simulator adapter."/>
                <type value="dynamic" default="step_0[connectivity]"/>
            </input>

            <input>
                <name value="chain_2"/>
                <label value="Second adapter from chain"/>
                <type value="tvb.adapters.visualizers.topographic.TopographicViewer"/>
            </input>
            <input overwrite="chain_2">
                <name value="data_0"/>
                <label value="Overwrite data_0 parameter of second adapter with the first release of the first adapter."/>
                <type value="dynamic" default="step_1[0]"/>
            </input>
            <input overwrite="chain_2">
                <name value="data_1"/>
                <label value="Overwrite data_1 parameter of second adapter with the second release of the first adapter."/>
                <type value="dynamic" default="step_1[1]"/>
            </input>
        </inputs>
    </portlet>

</tvb>
